using Silk.NET.Vulkan;

namespace grabs.VulkanMemoryAllocator
{
    [NativeTypeName("unsigned int")]
    public enum VmaDefragmentationFlagBits : uint
    {
        VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FAST_BIT = 0x1,
        VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT = 0x2,
        VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT = 0x4,
        VMA_DEFRAGMENTATION_FLAG_ALGORITHM_EXTENSIVE_BIT = 0x8,
        VMA_DEFRAGMENTATION_FLAG_ALGORITHM_MASK = VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FAST_BIT | VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT | VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT | VMA_DEFRAGMENTATION_FLAG_ALGORITHM_EXTENSIVE_BIT,
        VMA_DEFRAGMENTATION_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF,
    }
}
